--ISO_639-1_code=EN
--Wiki strings
--Note for translators: make sure html tags and things like %s and `%s` and %.1f and so on match the original; they are formating notation used by the wiki script to insert values, and the auto generated ones get this wrong.
--Infobox meta
wiki_infobox_stats_note="Note: This unit has some of its stats<br />redefined at the start of the game."
wiki_infobox_mod_source="Source:"
wiki_infobox_unitid="Unit ID:"
wiki_infobox_faction="Faction:"
wiki_infobox_factions="Factions:"
wiki_faction_uef="UEF"
wiki_faction_aeon="Aeon"
wiki_faction_cybran="Cybran"
wiki_faction_seraphim="Seraphim"
wiki_faction_nomads="Nomads"
wiki_faction_arm="Arm"
wiki_faction_core="Core"
wiki_infobox_tech="Tech level:"
wiki_tech_1="Tech 1"
wiki_tech_2="Tech 2"
wiki_tech_3="Tech 3"
wiki_tech_4="Experimental"
--Infobox defence
wiki_infobox_health="Health:"
wiki_infobox_armor="Armour:"
wiki_flag_invulnerable="Invulnerable"
wiki_infobox_shieldh="Shield health:"
wiki_infobox_shieldr="Shield radius:"
wiki_infobox_defflags="Flags:"
wiki_flag_untargetable="Untargetable"
wiki_flag_unselectable="Unselectable"
wiki_flag_nolife="Lifebars hidden"
wiki_flag_artilleryshield="Artillery shield"
wiki_flag_personalshield="Personal shield"
--Infobox economy
wiki_infobox_cost_e="Energy cost:"
wiki_infobox_cost_m="Mass cost:"
wiki_infobox_cost_t="Build time:"
wiki_infobox_maint_e="Maintenance cost:"
wiki_infobox_buildrate="Build rate:"
wiki_infobox_prod_e="Energy production:"
wiki_infobox_prod_m="Mass production:"
wiki_infobox_store_e="Energy storage:"
wiki_infobox_store_m="Mass storage:"
--Infobox intel
wiki_infobox_vision_r="Vision radius:"
wiki_infobox_w_vision_r="Water vision radius:"
wiki_infobox_radar_r="Radar radius:"
wiki_infobox_sonar_r="Sonar radius:"
wiki_infobox_omni_r="Omni radius:"
wiki_infobox_jammer_blips="Jammer blips (radii):"
wiki_infobox_cloak_r="Cloak radius:"
wiki_infobox_steath_radar_r="Radar stealth radius:"
wiki_infobox_steath_sonar_r="Sonar stealth radius:"
wiki_infobox_intelflags="Flags:"
wiki_ability_cloak="Cloak"
wiki_ability_radar_stealth="Radar stealth"
wiki_ability_sonar_stealth="Sonar stealth"
--Infobox motion
wiki_infobox_motion="Motion type:"
wiki_infobox_build_layers="Buildable layers:"
wiki_layer_land="Land"
wiki_layer_seabed="Seabed"
wiki_layer_sub="Sub"
wiki_later_water="Water"
wiki_layer_air="Air"
wiki_layer_orbit="Orbit"

wiki_infobox_movement_speed="Movement speed:"
wiki_infobox_fuel="Fuel:"
wiki_infobox_elevation="Elevation:"
wiki_infobox_transport_class="Transport class:"
wiki_infobox_transport_capacity="Transport capacity:"
--Infobox other
wiki_infobox_miscrad="Misc radius:"
wiki_misc_radius_note="Defined by the air staging radius value. Often used to indicate things without a dedicated range ring."
wiki_infobox_weapons="Weapons:"

--Brackets with an arbitrary string inserted
wiki_bracket_text=" (%s)"
wiki_infobox_details="Details"
--'%s' is for formatting in a string, '/s' is shortform for 'per second'
wiki_per_second="%s/s"
wiki_plus_per_second="+%s/s"

--Body lead text part 1
wiki_intro_name="\"%s\""
wiki_intro_nameless="This unnamed unit"
--Body lead text part 2
wiki_intro_factionless=" is a factionless"
wiki_intro_faction_other=" is an other faction"
wiki_intro_faction_aeon=" is an Aeon"
wiki_intro_faction_cybran=" is a Cybran"
wiki_intro_faction_uef=" is a UEF"
wiki_intro_faction_seraphim=" is a Seraphim"
wiki_intro_faction_nomads=" is a Nomads"
wiki_intro_faction_arm=" is an Arm"
wiki_intro_faction_core=" is a Core"
wiki_intro_multifaction=", which has multiple factions, is a"
--Body lead text part 3
wiki_intro_motion_type=" %s included in *%s*."
wiki_intro_ruleumt_air="aircraft unit"
wiki_intro_ruleumt_amphibious="seabed amphibious unit"
wiki_intro_ruleumt_amphibiousfloating="floating amphibious unit"
wiki_intro_ruleumt_biped="land unit"
wiki_intro_ruleumt_land="land unit"
wiki_intro_ruleumt_hover="hover unit"
wiki_intro_ruleumt_water="naval unit"
wiki_intro_ruleumt_surfacingsub="submarine unit"
wiki_intro_ruleumt_none="structure unit"
-- Body lead text part 4
-- in 'tdesc_b' tech level is inserted (ie 'tech 1'), in c&d tech level and short description is inserted (ie 'tech 1 assault bot')
wiki_intro_tdesc_a="It is an unclassified unit with no defined tech level."
wiki_intro_tdesc_b="It is an unclassified %s unit."
wiki_intro_tdesc_c="It is classified as a %s unit with no defined tech level."
wiki_intro_tdesc_d="It is classified as a %s unit."
wiki_intro_build_a=" It has no defined build description, and no categories to define common builders."
wiki_intro_build_b=" It has no defined build description."
wiki_intro_build_c="This unit has no categories to define common builders, however the build description for it is:"
wiki_intro_build_d="The build description for this unit is:"

wiki_toc_contents="Contents"

wiki_sect_abilities="Abilities"
wiki_abilities_hover_note="Hover over abilities to see effect descriptions."

wiki_sect_adjacency="Adjacency"
wiki_adjacency_part1="This unit counts as `%s` for adjacency effects from other structures. This theoretically means that it can be surrounded by exactly %s structures the size of a standard tech 1 power generator"
wiki_adjacency_part2_a=", which is accurate; meaning it can get the maximum intended buff effects"
wiki_adjacency_part2_b=", however it is actually larger; meaning it receives %.1f%% better buffs than would normally be afforded it"
wiki_adjacency_part2_c=", however it is actually smaller; meaning it receives %.1f%% weaker buffs than a standard structure of the same skirt size"
wiki_adjacency_part3=". "
wiki_adjacency_bonus="The adjacency bonus `%s` is given by this unit."

wiki_sect_balance="Balance"
wiki_balance_dynamic_script="A dynamic balance script changes the stats of this unit on game launch based on the stats of other units."
wiki_balance_stats_steam="Displayed stats are from when launched on the steam/retail version of the game."
wiki_balance_stats_affected="Stats effected are from the %s blueprint sections"
wiki_balance_stats_affected_singular="Stats effected are from the %s blueprint section"
wiki_balance_based=" and are based on %s"
wiki_balance_based_average=" and are based on an average of %s and %s"

wiki_sect_construction="Construction"
wiki_builders_note_steam="Build times from the Steam/retail version of the game:"
wiki_builders_by="Built by %s"

wiki_sect_orders="Order capabilities"
wiki_orders_note="The following orders can be issued to the unit:"

wiki_sect_engineering="Engineering"

wiki_sect_enhancements="Enhancements"
wiki_enhancements_slot_LCH="Left Arm"
wiki_enhancements_slot_Back="Back"
wiki_enhancements_slot_RCH="Right Arm"

wiki_sect_transport="Transport capacity"
wiki_sect_weapons="Weapons"
wiki_sect_vet="Veteran levels"
wiki_sect_videos="Videos"
